name: "HA Dashboard Extractor (Niek Tuytel)"
description: "Niek Tuytel's dashboard pre-renderer: animated WebP or MP4 videos, optimized for slow tablets."
version: "0.0.6"
slug: "ha_extractor"
url: "https://github.com/niektuytel/ha-extractor-app"
image: "ghcr.io/niektuytel/ha-extractor-app"
init: false
arch:
  - amd64
  - aarch64
map:
  - type: homeassistant_config
    read_only: false
    path: /config
options:
  url: "http://homeassistant:8123/lovelace?kiosk"
  token: ""
  width: 360
  height: 640
  zoom: 1
  screencast_quality: 60
  duration: 30
  wait_until_loaded: true
  delay_after_loaded: 2
  retain_profile: false
  profile_cache_clear_interval: 15
  cron: "*/30 * * * *"
  output_type: "webp"
  mp4_preset: "veryfast"
  framerate: 15
  encoder_threads: 1
  output_path: "/config/www/ha-extractor/output"
schema:
  url: str
  token: str?
  width: int
  height: int
  zoom: float
  screencast_quality: int
  duration: int
  wait_until_loaded: bool
  delay_after_loaded: int
  retain_profile: bool
  profile_cache_clear_interval: int
  cron: str
  output_type: list(webp|mp4)
  mp4_preset: list(ultrafast|superfast|veryfast|faster|fast|medium|slow|slower|veryslow)
  framerate: int
  encoder_threads: int
  output_path: str
